services:
  product_api:
    build: ./product_api
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./product_api:/home/node/app

  auth_api:
    build: ./auth_api
    environment:
      - PORT=3002
    ports:
      - "3002:3002"
    volumes:
      - ./auth_api:/home/node/app

  order_api:
    build: ./order_api
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    volumes:
      - ./order_api:/home/node/app

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - product_api
      - auth_api
      - order_api
